### ISSUE TITLE
If you supply a deps array (even if empty) - does that change the behavior?

### ISSUE THREAD

**Issue by CaptainN** [jorgeer/react-meteor-data-double-sub#1]
If you supply a deps array (even if empty) - does that change the behavior?

https://github.com/jorgeer/react-meteor-data-double-sub/blob/28ff97f0ee557b0546d92f2b9b90e97789b6354c/imports/ui/App.jsx#L16

**Comment by fumbleforce** [comment]
Thanks, that does make the difference, yeah!

**Comment by CaptainN** [comment]
Its great that worked as a workaround, but this is probably still a bug we should look in to.
